### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by markushopkins** [vkelk/uspto_trademark_parser#1]
Hi there,

I am interested in contributing to this, but it would be helpful to have the database schema so I could test out the current functionality.  If that's something you could add to the repo, that would be greatly appreciated. Thanks!

**Comment by vkelk** [comment]
Hi,
I have added the schema creation script. https://github.com/vkelk/uspto_trademark_parser/blob/master/schema_create.sql

Feel free to fork / contribute.

**Comment by markushopkins** [comment]
Thank you!
